#!/bin/sh -e

/usr/local/bin/gotemp -f /etc/frps.toml.tpl -o /etc/frps.toml

sv start portmanager || exit 1

if [ ! -z "${FRPS_LETSENCRYPT_EMAIL}" ]; then

sv start acmeproxy || exit 1

fi

exec /usr/local/bin/frps -c /etc/frps.toml 2>&1
